name: Build iOS App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Install dependencies (if using CocoaPods)
      run: |
        if [ -f "Podfile" ]; then
          sudo gem install cocoapods
          pod install
        fi
        
    - name: Install dependencies (if using Swift Package Manager)
      run: |
        if [ -f "Package.swift" ]; then
          xcodebuild -resolvePackageDependencies
        fi
        
    - name: Build
      run: |
       xcodebuild -project explt.xcodeproj -arch arm64e,arm64 -scheme explt -configuration Release -destination 'platform=iOS,name=iPhone,arch="arm64,arm64e"' -archivePath build/App.xcarchive archive CODE_SIGNING_ALLOWED=NO
    
    - name: Export IPA
      run: |
        # Create export options plist
        cat > ExportOptions.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>development</string>
            <key>teamID</key>
            <string>9PZG728AQ8</string>
            <key>compileBitcode</key>
            <false/>
            <key>uploadSymbols</key>
            <true/>
            <key>signingStyle</key>
            <string>automatic</string>
        </dict>
        </plist>
        EOF
        
        # Export IPA
        xcodebuild -exportArchive \
                   -archivePath build/App.xcarchive \
                   -exportPath build/ \
                   -exportOptionsPlist ExportOptions.plist CODE_SIGNING_ALLOWED=NO
                   
    - name: Upload IPA as artifact
      uses: actions/upload-artifact@v4
      with:
        name: iOS-App-IPA
        path: build/*.ipa
        retention-days: 30
        
    - name: Upload dSYM as artifact
      uses: actions/upload-artifact@v4
      with:
        name: iOS-App-dSYM
        path: build/*.app.dSYM.zip
        retention-days: 30
