name: Build iOS App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Install dependencies (if using CocoaPods)
      run: |
        if [ -f "Podfile" ]; then
          sudo gem install cocoapods
          pod install
        fi
        
    - name: Install dependencies (if using Swift Package Manager)
      run: |
        if [ -f "Package.swift" ]; then
          xcodebuild -resolvePackageDependencies
        fi
        
    - name: Build
      run: |
        xcodebuild -project explt.xcodeproj -scheme explt -configuration Release -destination 'platform=iOS, name=Any iOS Device' build CODE_SIGNING_ALLOWED=NO
    
    - name: Upload app as artifact
      uses: actions/upload-artifact@v4
      with:
        name: iOS-App-Simulator
        path: build/Release-iphonesimulator/explt.app
        retention-days: 30
